FROM gradle:jdk11-slim as builder
USER root
ADD . /builder
WORKDIR /builder
RUN gradle build shadowJar --no-daemon

FROM navikt/java:11
ENV JAVA_OPTS="-Dlogback.configurationFile=logback-remote.xml"
COPY --from=builder /builder/build/libs/*.jar app.jar
