kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{name}}
  namespace: integrasjon
  labels:
    team: integrasjon
spec:
  image: {{image}}
  ingresses:
    {{#each ingresses}}
     - "{{this}}"
    {{/each}}
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  port: 8080
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  env:
    - name: TOPIC_CREATION_ENABLED
      value: "true"
